# Generated by Django 3.0.14 on 2021-09-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=200)),
                ('primary_investigator', models.CharField(max_length=200)),
                ('submit_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
